# Generated by Django 5.0.7 on 2024-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('raw_data', models.BinaryField()),
                ('status', models.IntegerField(default=0)),
                ('code', models.BinaryField(blank=True, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('status_updated_at', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
